sudo: required
dist: trusty
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.7.1
before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv -f docker-compose /usr/local/bin
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce
script:
  - docker-compose build test
  - docker-compose run test
  - docker-compose build coverage
  - docker-compose run coverage
