sudo: false
language: cpp
before_script: 
  - git submodule update --init --recursive
  - autoreconf -if
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - valgrind
script:
  - CXX=g++-4.8 ./configure
  - make test
  - valgrind --leak-check=full --error-exitcode=5 ./tests/arg3fmt_test
 
