version: '2'
services:
  test:
    image: coda_format_test
    build:
      context: .
      args:
          CMAKE_DEFINES: -DCMAKE_BUILD_TYPE=Release -DENABLE_MEMCHECK=ON -DCMAKE_CXX_COMPILER=g++
    environment:
      - TRAVIS_JOB_ID
    working_dir: /usr/src/docker-build
    command: make test ARGS=-V
  coverage:
    extends: test
    image: coda_format_coverage
    build:
      args:
          CMAKE_DEFINES: -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER=g++
    command: make coda_format_coverage_coveralls
